apiVersion: v1
kind: Secret
metadata:
  name: {{ include "student-tracker.fullname" . }}-secret
  labels:
    {{- include "student-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  VAULT_ADDR: aHR0cDovLzQ0LjIwNC4xOTMuMTA3OjgyMDA=  # http://44.204.193.107:8200 (base64)
  VAULT_ROLE_ID: ZjdhZjU4YjEtNWMyMi03YzJkLWM2NTktMDQyNWQ5Y2U5NGIy  # f7af58b1-5c22-7c2d-c659-0425d9ce94b2 (base64)
  VAULT_SECRET_ID: ZDVmNzM2ZGEtNzg1Yi04ZjVjLTkyNTgtNDhkNWQ3YzQzYzA2  # d5f736da-785b-8f5c-9258-48d5d7c43c06 (base64)
