apiVersion: v1
kind: Service
metadata:
  name: student-tracker-service
  namespace: my-app
spec:
  selector:
    app: student-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
